"""Generate the model card (Bloc 4, DPIA #2 commitment).

Reads ``ml/models/metrics.json`` + the promoted bundle and writes a Markdown
model card to both ``docs/bloc4-ai-mlops/model-card.md`` and ``ml/models/model_card.md``.
The card documents intended use, data, metrics, the SHAP explainability artefact,
and the governance posture (no PII in features, transparency, human-in-the-loop).
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from config import CURRENT_MODEL, METRICS_FILE, ML_DIR
from features import CALENDAR_FEATURES, LAG_FEATURES, PII_COLUMNS, ROLLING_FEATURES

DOCS_CARD = ML_DIR.parent / "docs" / "bloc4-ai-mlops" / "model-card.md"
ML_CARD = ML_DIR / "models" / "model_card.md"


def _load_metrics() -> dict:
    if METRICS_FILE.exists():
        return json.loads(METRICS_FILE.read_text())
    return {}


def build_card() -> str:
    m = _load_metrics()
    g = m.get("global", {})
    per_cat = m.get("per_category", {})
    version = m.get("version", "unknown")
    trained_at = m.get("trained_at", "unknown")
    date_range = m.get("date_range", ["?", "?"])

    rows = "\n".join(
        f"| {c} | {v.get('mape', '—')} | {v.get('smape', '—')} | {v.get('rmse', '—')} |"
        for c, v in sorted(per_cat.items())
    )

    return f"""# Model Card — NOUREDDINE Demand Forecaster

> Generated by `ml/src/model_card.py` on {datetime.now(timezone.utc).isoformat()}.
> Do not edit by hand — regenerate after each training run.

## Model details
- **Type:** LightGBM gradient-boosted regression (`objective=regression`, `metric=rmse`).
- **Task:** forecast **daily units sold per product category** (category × day).
- **Horizon:** up to 30 days. **Version:** `{version}` (trained at {trained_at}).
- **Training window:** {date_range[0]} → {date_range[1]}.
- **Validation:** time-based split, last 30 days held out.

## Intended use
- **Decision support** for stock and treasury planning against Islamic-calendar
  seasonality (Ramadan, Eid al-Fitr, Eid al-Adha, Nikah season) and retail peaks
  (Black Friday, Summer Sale).
- **Not** an automated ordering system — a human reviews forecasts in the Streamlit
  app before acting (human-in-the-loop, DPIA #2).

## Features (governed — NO PII, DPIA #2)
- **Calendar (from `oltp.calendar_events`, fixed windows — Hijri dates never recomputed):**
  {", ".join(CALENDAR_FEATURES)}.
- **Autoregressive per category:** {", ".join(LAG_FEATURES + ROLLING_FEATURES)}.
- **Category** as a native LightGBM categorical feature.
- **Explicitly excluded** (test-enforced): {", ".join(sorted(PII_COLUMNS))}.

## Performance (validation, last 30 days)
- **Global:** MAPE = **{g.get('mape', '—')}**, sMAPE = {g.get('smape', '—')}, RMSE = {g.get('rmse', '—')}.

| Category | MAPE | sMAPE | RMSE |
|----------|------|-------|------|
{rows}

## Explainability
- Global SHAP summary plot: `ml/models/shap_summary.png` (calendar proximity and
  recent demand dominate, as expected for event-driven retail).

## Governance & ethics
- **DPIA #2 (AI forecasting):** features are aggregate, category-level only. No
  `customer_id`, email, name or address ever enters the training matrix
  (`features.assert_no_pii`, enforced by `tests/test_features.py`).
- **Transparency:** SHAP plot + this card published with each version.
- **Human-in-the-loop:** retraining is gated (promote only if MAPE within tolerance)
  and admin-triggered via `/retrain`; Streamlit is decision-support, not auto-action.
- **Quality gate (P-04):** retraining is skipped if upstream Bloc 3 data-quality runs failed.

## Limitations
- Trained on **synthetic** demand for the PFE; absolute values are illustrative.
- Assumes the governed calendar windows remain the single source of seasonality truth.
"""


def main():
    card = build_card()
    DOCS_CARD.parent.mkdir(parents=True, exist_ok=True)
    DOCS_CARD.write_text(card)
    ML_CARD.write_text(card)
    print(f"Model card written -> {DOCS_CARD} and {ML_CARD}")


if __name__ == "__main__":
    main()
